### ISSUE TITLE
Ginkgo Cadx doesn't seem to be able to retrive data from a Orthanc PACS server (Regression versus 3.7.1)

### ISSUE THREAD

**Issue by gerddie** [gerddie/ginkgocadx#13]
Uploading works, but downloading gives errors depending on the transfer method: 

With the MOVE method Ginkgpcadx reports 

```
E: Error Downloading study: Exception in component GIL/PACS :
E: Failed: UnableToProcess
E: Store SCP Failed: 0006:020e DIMSE Failed to send message
E: 0006:031d TCP I/O Error (Broken pipe) occurred in routine: writeDataPDU
E: DIMSE failure (aborting association): 0006:020e DIMSE Failed to send message
E: 0006:031d TCP I/O Error (Broken pipe) occurred in routine: writeDataPDU
```

and Orthnac reports:  

```
W0302 14:08:55.689193 OrthancMoveRequestHandler.cpp:171] Move-SCU 
     request received for AET "GINKGO"
E0302 14:09:55.837689 DicomUserConnection.cpp:159] 
     DicomUserConnection: Peer aborted Association (or never connected)
E0302 14:09:55.837942 MoveScp.cpp:183] IMoveRequestHandler Failed: 
     Error in the network protocol
```

With the GET method GinkgoCADx reject the request immediately with: 

```
E: Error Downloading study: Exception in component GIL/PACS :
E: DIMSE No valid Presentation Context ID
```

**Comment by gerddie** [comment]
Could [this discussion](https://github.com/gerddie/ginkgocadx/issues/13) be related?

**Comment by gerddie** [comment]
The old version 3.7.1 that can be downloaded from sourceforge does retrieve the data. So it's either a dicom-3.6.1_pre\* issue, or I did something wrong when I converted the code to use the new library.

**Comment by gerddie** [comment]
[Information on how to debug the client/server layout](http://support.dcmtk.org/redmine/projects/dcmtk/wiki/Howto_PACSDebuggingWithDCMTK)  (thanks Michael Onken.)

**Comment by gerddie** [comment]
Server tested with 

```
movescu -v -S -aec ORTHNAC -aet GINKGO -aem GINKGO --port 11112 -od . localhost 4242  -k StudyInstanceUID=XXXX 
```

shows that the connection is working, do DCMTK is fine.

**Comment by gerddie** [comment]
It is actually a threading problem: When the request is sent, Ginkgo apparently blocks, and the  Orthanc  from is only received after  Orthanc  already hung up.

**Comment by sunilm12** [comment]
Hello Gerddie,
I am using Ginkgo CADx 3.7.1.1573 ( 32 bits)  on windows 10. Just installed it over the weekend. I am able to connect the Orthac server. Upload the images. However when I try to download it , I am getting the same error : Error downloading the study: Exception in component GIL/PACS. Failed: Unable to process.
Please advice. 
thank you in advance for any help here.

**Comment by gerddie** [comment]
Probably the bug is fixed in a a newer version (since I closed this), but as you might have notes in the README file accompanying this git repository, I do only keep the software alive on a voluntary basis and work only on Linux based system, therefore I can not really help you here, especially not with bugs related to these old versions that were provided by the original developers.
