### ISSUE TITLE
Coverity has discovered 154 problems in the code

### ISSUE THREAD

**Issue by gerddie** [gerddie/ginkgocadx#15]
This bug is here to reference changes to these in the commits.

**Comment by onlyjob** [comment]
What's "Coverity"?

**Comment by onlyjob** [comment]
OK, this seems relevant: https://scan.coverity.com/github

**Comment by gerddie** [comment]
The overview of the current build is [here](https://scan.coverity.com/projects/ginkgocadx?tab=overview). 

BTW: Github integration is not very relevant at this point, because this is mostly for using  [travis-ci](https://travis-ci.org/) to build and upload, and the [travis-ci build environment](https://docs.travis-ci.com/user/trusty-ci-environment) uses a rather old Ubuntu (14.04 at best), which has an old version of ITK.

**Comment by onlyjob** [comment]
> The overview of the current build is [here](https://scan.coverity.com/projects/ginkgocadx?tab=overview).

That page requires sign-in unfortunately... Also Coverity is proprietary... :(
Does it have free alternatives?

**Comment by gerddie** [comment]
Here is the [the public page](https://scan.coverity.com/projects/ginkgocadx). Well, Coverity is free-as-in-beer for developers of free software ... but yes, one has to run their proprietary tool.   

The only free alternative I can think of is using clang  to compile the code with the static analyzer, it's not as thorough though.

**Comment by gerddie** [comment]
Well, and some errors would also be caught by _valgrind_.

**Comment by onlyjob** [comment]
Thought I'd mention _cppcheck_.  :)

**Comment by gerddie** [comment]
All issues resolved with the exception of #16.
