### ISSUE TITLE
How to enable 3d reconstructruction

### ISSUE THREAD

**Issue by ribalda** [gerddie/ginkgocadx#20]
Hello

I am trying to enable 3d reconstruction via:

Tools -> Settings -> Profiles -> New/Edit; Set 3D Reconstruction: "true", 

But I cannot find the 3D reconstruction option.

I am using Linux 64 bits. Any hint?

Thanks!

**Comment by gerddie** [comment]
Which version are you using? I have only access to what Metaemotion released as open source software, and as far as I can see there is no 3D reconstruction implemented. It has only a TODO in the code and an empty interface definition that might indicate that either the non-free version of the software implements this, or that it was a planned feature that never got implemented. 
In the open source version that can be compiled from the code here there is also no option "3D Reconstruction" in the profile settings.

**Comment by ribalda** [comment]
I tried on both, git clone master and the binary from http://ginkgo-cadx.com/en/

I have seen youtube videos mentioning it, and also the enable procedure from https://sourceforge.net/projects/ginkgocadx/files/3.5.0/

Too bad it is not implemented :(

**Comment by gerddie** [comment]
I see. Well, when I have time for it I might actually implement it. I've developed another tool [mialmpick](https://sourceforge.net/p/mia/wiki/lmpick/) that does CT surface rendering of 3D data, but can't read DICOM files.
