### ISSUE TITLE
Under Ubuntu 16.04 libproj is required for compiling

### ISSUE THREAD

**Issue by ghost** [gerddie/ginkgocadx#25]
`apt-get install libproj-dev` is also required:

```
[ 99%] Linking CXX static library libvisualizator.a
[ 99%] Built target visualizator
Scanning dependencies of target ginkgocadx
make[2]: *** No rule found to create „/usr/lib/x86_64-linux-gnu/libproj.so“, 
  required by „ginkgocadx/ginkgocadx“. End.
```

**Comment by gerddie** [comment]
Yes, this is actually a bug in libvtk6-dev that has since been fixed at least in [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819714). Unfortunately, Ubuntu 16.04 doesn't yet carry that version.

**Comment by ghost** [comment]
Alright, then this is not an issue of ginkgocadx itself and I can close here. You may want to note that in the readme though.
