### ISSUE TITLE
Series left panel displays incorrectly

### ISSUE THREAD

**Issue by Niujk** [gerddie/ginkgocadx#29]
Using v3.8.4, [trusty backport](https://launchpad.net/%7Egert-die/+archive/ubuntu/ginkgocadx-trusty), left side panel appears 'pixeled'. The RX photo itself is showing properly.

Better watched than explained.
![](https://cloud.githubusercontent.com/assets/7169204/22819755/cf53c256-ef73-11e6-9953-9100f11e81be.png)

**Comment by gerddie** [comment]
A anonymized example image would be helpful, because with the images I have, I can't reproduce this.

**Comment by Niujk** [comment]
I'm on it, will report back editing here asap.
Edit: Few programs I tested to anonymize the DICOM files are not working, any thoughts? 
Edit 2: [Got it!](https://github.com/gerddie/ginkgocadx/files/766541/AnonymousImage.zip), for those interested I used [mipav](https://mipav.cit.nih.gov/pubwiki/index.php/Main_Page)

**Comment by gerddie** [comment]
Well, for me the thumbnail looks fine (see pic), and also the data inside the image is not very special (i.e. Tags 0028:1050 and 0028:1051. Where these tumbnails created with the current version, or at least 3.7.1 or did they display well in 3.7.1? 

![ginkgo-snapshot](https://cloud.githubusercontent.com/assets/2786969/22838617/4bf709c4-efc6-11e6-9eb6-b2597e8d51ba.png)

BTW: When you edit a comment later, I don't get an e-mail notification, so in this case I just saw in the github notification area that you had changed the last message adding that you had a anonymized pic.

**Comment by Niujk** [comment]
Well thumbnails were created in v3.6.X and they displayed properly, same in v3.7.1 ...

Just thought about setting up our PACS server and try again with a new image.

**Comment by Niujk** [comment]
Fixed. I was using a 3.6.X folder. Thank you, awesome work as always.

Downloading the images from PACS from v3.8.4 fixes the thumbnails issue.
