### ISSUE TITLE
Problem building GinkgoCADx

### ISSUE THREAD

**Issue by Niujk** [gerddie/ginkgocadx#38]
Tried to follow the instructions to build the last version of GinkgoCADx as here:

> With these prerequisites available run cmake on the Ginkgo CADx source tree and then use the selected build system to build the software. After the software was sucessfully compiled run the install target.

Had a problem using **make** inside the _build-dir_ directory, almost at the end of it. Here's the original log:

```
[ 99%] Built target visualizator
Scanning dependencies of target ginkgocadx
[100%] Building CXX object ginkgocadx/CMakeFiles/ginkgocadx.dir/main.cpp.o
make[2]: *** No hay ninguna regla para construir el objetivo '/usr/lib/x86_64-linux-gnu/libproj.so', necesario para 'ginkgocadx/ginkgocadx'.  Alto.
CMakeFiles/Makefile2:174: fallo en las instrucciones para el objetivo 'ginkgocadx/CMakeFiles/ginkgocadx.dir/all'
make[1]: *** [ginkgocadx/CMakeFiles/ginkgocadx.dir/all] Error 2
Makefile:127: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
```
Which basically it translates to:
 ```
[ 99%] Built target visualizator
Scanning dependencies of target ginkgocadx
[100%] Building CXX object ginkgocadx/CMakeFiles/ginkgocadx.dir/main.cpp.o
make[2]: *** There is no rule to build the target '/usr/lib/x86_64-linux-gnu/libproj.so', needed for 'ginkgocadx/ginkgocadx'.  Stop.
CMakeFiles/Makefile2:174: failure in the instructons for target 'ginkgocadx/CMakeFiles/ginkgocadx.dir/all'
make[1]: *** [ginkgocadx/CMakeFiles/ginkgocadx.dir/all] Error 2
Makefile:127: failure in the instructions for target 'all'
make: *** [all] Error 2
```

What am I missing? Do I need any further parameters when I use **make**?

**Comment by gerddie** [comment]
This too is an old bug that results from VTK not having been build against the installed version of libproj, 
see [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819714).

**Comment by gerddie** [comment]
A corrected version of VTK 6.2 and also ginkgocadx 3.8.4 are now in the [xenial-ports](https://launchpad.net/~gert-die/+archive/ubuntu/xenial-mia) ppa.

**Comment by Niujk** [comment]
First of all, thanks for your time and effort, you've been my clinic's saviour this months so far.
But actually the [build failed](https://launchpadlibrarian.net/346040074/buildlog_ubuntu-xenial-amd64.ginkgocadx_3.8.4-1~xeniammia1_BUILDING.txt.gz) and I'm unable to download the package now.

**Comment by gerddie** [comment]
My bad, the problem is actually in the libvtk6-dev package, and I wrongly assumed forcing a rebuild against the latest libproj-dev would do, but it was the missing dependency on that package in libvtk6-dev that made the build fail (that was also the Debian bug three years ago). launchpad currently builds a new upload of vtk6 fixing this and then I'll trigger a new build of ginkgocadx.

**Comment by gerddie** [comment]
Okay, this time it really built.

**Comment by Niujk** [comment]
Worked like a charm, GinkgoCADx v3.8.4 working in my Ubuntu 16.04LTS correctly.

Thanks again Mr. Wollny, much appreciated!
