### ISSUE TITLE
switch between axial/sagittal/coronal view

### ISSUE THREAD

**Issue by pdeman** [gerddie/ginkgocadx#41]
hi,

is there a possibility to switch between axial/sagittal/coronal view ?

by default the image that I am looking at is in sagittal orientation but I'ld like to see it in other orientation as well

**Comment by gerddie** [comment]
I don't think that is possible. AFAIK while ginkgocadx is aware of series of images, it does not handle them as 3D data sets internally, so the view is not really changeable. For doing so you might consider having a look at [amide](http://amide.sourceforge.net/) or [itksnao](http://www.itksnap.org/pmwiki/pmwiki.php)

**Comment by pdeman** [comment]
thanks. I'll try amide.
