### ISSUE TITLE
Does not compile if DCMTK was build with DCMTK_ENABLE_STL

### ISSUE THREAD

**Issue by FlorianFranzen** [gerddie/ginkgocadx#43]
```OFIterator``` is not defined if DCMTK was build with DCMTK_ENABLE_STL and therefore break compilation with following error:

```
/build/source/cadxcore/main/controllers/dcmtk/dicomstoreassociation.cpp: In member function 'void GIL::DICOM::DicomStoreAssociation::Store(GIL::DICOM::DicomStoreAssociation::ListaRutas, const GNC::GCS::Ptr<DicomServer>&, std::__cxx11::string, GNC::IProxyNotificadorProgreso*, GIL::DICOM::TipoTransferSyntaxEnvio)':
/build/source/cadxcore/main/controllers/dcmtk/dicomstoreassociation.cpp:1045:38: error: 'OFIterator' was not declared in this scope
                                 for (OFIterator<OFString> itsc =sopClassUIDList.begin(); itsc != sopClassUIDList.end(); ++itsc) {
                                      ^~~~~~~~~~
```
I would therefore propose to abort configuration with a proper error message if DCMTK_ENABLE_STL is set (after the call to find_package). Adding a check for DCMTK_ENABLE_CXX11 being set would probably also be a good idea.

**Comment by gerddie** [comment]
Unfortunately, I currently don't have much time to look into this  right now. Would you consider preparing a PR?
