### ISSUE TITLE
[Packaging] Make this program available as flatpak package on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [gerddie/ginkgocadx#51]
Hi. It is very useful to make this program available as flatpak package on FlatHub. This way you will make this program available for almost any Linux distros & users, because flatpak is universal generic Linux package with secure features by default & easy & convenient installation & automatic update mechanism.

Please note the following:
    1. home page of FlatHub is:
    https://www.flathub.org/home
    2. FlatHub repositories are at:
    https://github.com/flathub
   3.  when some one like to add package to FlatHub, she/he need to open PR at:
    https://github.com/flathub/flathub/pulls
    4. FlatHub differ from snap by being allow any one to package not only developers of packages. So packages on FlatHub are of 2 types: those packaged by developer(s) of program, & those packaged by other peoples.
    5. all packages on FlatHub are signed .....
    6. even if person other than the original developer(s) maintain the package on FlatHub, FlatHub team try as much as possible to make developer(s) authorized to repositories at least to monitor & follow up the packaging ......
    7. FlatHub allow both open & closed source packages. But regarding open source packages, the FlatHub team insisting on packager to make them deterministic (reproducible).

**Comment by onlyjob** [comment]
Why bother with redundant packaging when Ginkgocadx is available from native Debian repositories? Let upstream focus on developing of the software and let downstream package maintainers to integrate with GNU/Linux distros.

**Comment by Nokia808** [comment]
@onlyjob 
Because I'm not using Debian based Linux. I'm I Fedora Linux user. Also, because flatpak is a universal Linux packaging system support almost all Linux distros & users

**Comment by gerddie** [comment]
Well, two notes: On one hand I don't really have the time to deal with building flatpack packages or snaps, but, yes it would  make sense, because ginkgocadx relies on OpenGL Compat features and hence VTK < 8.0 build with OpenGL and not OpenGL2, and because of this, maintainance within the distros becomes more and more difficult. 
Updating ginkocadx to not require a Compat context is also something I'm not able to do (no time, because since I changed my job, I'm completely outside medical imaging).

**Comment by Nokia808** [comment]
@gerddie 
Thank you for your response. Other person can make flatpak. Unfortunately I'm not programmer neither packager, but just a medical personal (Neurologist) using Linux ....

**Comment by boskar** [comment]
@Nokia808 I used to like ginkgo a lot, but currently for a neurologist there are some good alternatives for ginkgo, weasis is surprisingly good if You install it, and Radiant works great under wine. although ginkgo is still a great piece of software.

**Comment by onlyjob** [comment]
@Nokia808, IMHO you should definitely consider using Debian instead of Fedora. Not only Debian is superior in every way but also we have *Debian Med*:

  * https://blends.debian.org/med/tasks/
  * https://www.debian.org/devel/debian-med/
  * https://wiki.debian.org/DebianMed
